package mockerylint

import (
	"errors"
	"go/ast"
	"go/token"
	"go/types"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

// New creates a new Analyzer.
func New() *analysis.Analyzer {
	return &analysis.Analyzer{
		Name:     "mockerylint",
		Doc:      "Encourage good practices for mocks generated by Mockery",
		Requires: []*analysis.Analyzer{inspect.Analyzer},
		Run:      run,
	}
}

func run(pass *analysis.Pass) (any, error) {
	visitor, ok := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	if !ok {
		return nil, errors.New("missing inspect.Analyzer requirement")
	}

	filter := []ast.Node{
		(*ast.CallExpr)(nil),
		(*ast.UnaryExpr)(nil),
	}

	visitor.WithStack(filter, func(n ast.Node, push bool, stack []ast.Node) bool {
		if push {
			visitWithContext(pass, n, stack)
		}

		return true
	})

	return nil, nil
}

func visitWithContext(pass *analysis.Pass, node ast.Node, stack []ast.Node) {
	if isGenerated(pass, node.Pos()) {
		return
	}

	switch n := node.(type) {
	case *ast.CallExpr:
		visitCallExpr(pass, n, stack)
	case *ast.UnaryExpr:
		visitUnaryExpr(pass, n)
	}
}

func visitCallExpr(pass *analysis.Pass, call *ast.CallExpr, stack []ast.Node) {
	checkNewMockPattern(pass, call)

	// Check for method calls on mock objects
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return
	}

	checkMockMethodCall(pass, call, selector, stack)
}

func checkNewMockPattern(pass *analysis.Pass, call *ast.CallExpr) {
	ident, ok := call.Fun.(*ast.Ident)
	if !ok || ident.Name != "new" {
		return
	}

	if len(call.Args) == 1 && isMockType(pass.TypesInfo.TypeOf(call.Args[0])) {
		pass.Reportf(call.Pos(), "use factory to initialise mock")
	}
}

func checkMockMethodCall(pass *analysis.Pass, call *ast.CallExpr, selector *ast.SelectorExpr, stack []ast.Node) {
	switch selector.Sel.Name {
	case "On":
		if isMock(selector.X, pass.TypesInfo) {
			pass.Reportf(call.Pos(), "use .EXPECT instead of .On")
		}

	case "Test":
		if isMock(selector.X, pass.TypesInfo) {
			pass.Reportf(call.Pos(), ".Test() can be removed when using mock factory")
		}

	case "AssertExpectations":
		if isMock(selector.X, pass.TypesInfo) {
			pass.Reportf(call.Pos(), ".AssertExpectations() can be removed when using mock factory")
		}

	case "Return", "RunAndReturn":
		if isMockExpectationCall(selector.X, pass.TypesInfo) && needsTimesCall(stack) {
			pass.Reportf(call.Pos(), `expectation should call .Maybe(), .Once(), .Twice(), or .Times(N)`)
		}
	}
}

// isTimesMethod matched the expectation methods that constrain how many times a mocked
// method is expected to be called.
func isTimesMethod(name string) bool {
	switch name {
	case "Maybe", "Once", "Twice", "Times":
		return true
	default:
		return false
	}
}

// needsTimesCall reports whether the expectation call at the top of stack is missing
// a call to one of the timesMethods.
//
// The stack is walked outwards along the expectation chain. A times method anywhere
// in the chain satisfies the rule, and so does an expectation that escapes into a
// variable, return value or argument, because a times method may be called on it
// elsewhere. Only a chain whose value is discarded can be reported with confidence.
func needsTimesCall(stack []ast.Node) bool {
	if len(stack) == 0 {
		return false
	}

	node := stack[len(stack)-1]
	parents := stack[:len(stack)-1]

	for i := len(parents) - 1; i >= 0; i-- {
		switch parent := parents[i].(type) {
		case *ast.ParenExpr:
			// Parentheses do not break the chain.

		case *ast.SelectorExpr:
			// The expectation is the receiver of another chained method.
			if parent.X != node {
				return false
			}

			if isTimesMethod(parent.Sel.Name) {
				return false
			}

		case *ast.CallExpr:
			// The chained method is being called, e.g. the parentheses in .Run(f). If
			// the expectation is an argument instead, it escapes.
			if parent.Fun != node {
				return false
			}

		case *ast.ExprStmt:
			// The chain ends without a times method and its value is discarded.
			return true

		default:
			// The expectation escapes, so it cannot be judged in isolation.
			return false
		}

		node = parents[i]
	}

	return false
}

func visitUnaryExpr(pass *analysis.Pass, unary *ast.UnaryExpr) {
	// Check for &MockExample{} pattern
	if unary.Op == token.AND {
		if comp, ok := unary.X.(*ast.CompositeLit); ok {
			if isMockType(pass.TypesInfo.TypeOf(comp)) {
				pass.Reportf(unary.Pos(), "use factory to initialise mock")
			}
		}
	}
}

func isMock(expr ast.Expr, info *types.Info) bool {
	typ := info.TypeOf(expr)
	if typ == nil {
		return false
	}

	// Check if it's the mock.Mock type itself (e.g., mock.Mock.Test())
	if typ.String() == "github.com/stretchr/testify/mock.Mock" {
		return true
	}

	// Check if embeds mock.Mock
	if isMockType(typ) {
		return true
	}

	// For identifiers, also check the object's type
	if ident, ok := expr.(*ast.Ident); ok {
		if obj := info.ObjectOf(ident); obj != nil {
			return isMockType(obj.Type())
		}
	}

	return false
}

func isMockType(typ types.Type) bool {
	if typ == nil {
		return false
	}

	// Handle pointer types
	ptr, ok := typ.(*types.Pointer)
	if ok {
		typ = ptr.Elem()
	}

	// Get the underlying struct
	var structType *types.Struct
	switch t := typ.(type) {
	case *types.Struct:
		structType = t
	case *types.Named:
		if s, ok := t.Underlying().(*types.Struct); ok {
			structType = s
		}
	}

	if structType == nil {
		return false
	}

	// Check if the struct has an embedded mock.Mock field
	for i := range structType.NumFields() {
		field := structType.Field(i)
		if !field.Embedded() {
			continue
		}

		if field.Type().String() == "github.com/stretchr/testify/mock.Mock" {
			return true
		}
	}

	return false
}

func isGenerated(pass *analysis.Pass, pos token.Pos) bool {
	file, ok := fileFromPos(pass, pos)
	if !ok {
		return false
	}

	return ast.IsGenerated(file)
}

func fileFromPos(pass *analysis.Pass, pos token.Pos) (*ast.File, bool) {
	for _, file := range pass.Files {
		if file.FileStart <= pos && file.FileEnd >= pos {
			return file, true
		}
	}

	return nil, false
}

// isMockExpectationCall checks if the expression is a call to a mock expectation method
// (e.g., the result of m.EXPECT().Example(...)).
func isMockExpectationCall(expr ast.Expr, info *types.Info) bool {
	typ := info.TypeOf(expr)
	if typ == nil {
		return false
	}

	// Check if the type is a pointer to a type that embeds *mock.Call
	// The pattern is: *MockExample_Example_Call which embeds *mock.Call
	ptr, ok := typ.(*types.Pointer)
	if !ok {
		return false
	}

	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return false
	}

	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return false
	}

	// Check if the struct has an embedded *mock.Call field
	for i := range structType.NumFields() {
		field := structType.Field(i)
		if !field.Embedded() {
			continue
		}

		fieldType := field.Type()
		if fieldType.String() == "*github.com/stretchr/testify/mock.Call" {
			return true
		}
	}

	return false
}
