package mockerylint

import (
	"errors"
	"go/ast"
	"go/constant"
	"go/token"
	"go/types"
	"slices"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

// The rules the analyzer applies. Each name matches the heading of its section in the
// README, so a diagnostic categorised with one resolves to that section. A driver naming
// a rule, such as the flags of the command, should use these rather than its own copies.
const (
	RuleUseFactory  = "usefactory"
	RuleUseExpecter = "useexpecter"
	RuleUseTimes    = "usetimes"
	RuleNoAnything  = "noanything"
)

// Options records which of the rules the analyzer applies. The zero value applies none, so
// a configuration built by hand should start from DefaultOptions and turn off what it does
// not want.
type Options struct {
	UseFactory  bool
	UseExpecter bool
	UseTimes    bool
	NoAnything  bool
}

// DefaultOptions returns the default configuration for the analyzer.
func DefaultOptions() *Options {
	return &Options{
		UseFactory:  true,
		UseExpecter: true,
		UseTimes:    true,
		NoAnything:  true,
	}
}

// enabled reports whether the named rule is applied. A name with no field of its own is
// applied, so a rule added without one keeps the behaviour it had before rather than
// disappearing from the output unannounced.
func (o *Options) enabled(rule string) bool {
	switch rule {
	case RuleUseFactory:
		return o.UseFactory
	case RuleUseExpecter:
		return o.UseExpecter
	case RuleUseTimes:
		return o.UseTimes
	case RuleNoAnything:
		return o.NoAnything
	default:
		return false
	}
}

// linter holds the configuration the checks share.
type linter struct {
	opts *Options
}

// report records a diagnostic against the rule that produced it, unless that rule is
// turned off. Every check reports through here, so no disabled rule can reach the
// output. A driver resolves the documentation for a categorised diagnostic as "#" +
// category relative to the URL of the analyzer, which is the rule's heading in the
// README.
//
// Any fixes given are offered to the driver, which applies them with -fix or presents
// them as code actions. A check that cannot rewrite an occurrence mechanically passes
// none and reports the diagnostic on its own.
func (l *linter) report(
	pass *analysis.Pass,
	rule string,
	pos token.Pos,
	message string,
	fixes ...analysis.SuggestedFix,
) {
	if !l.opts.enabled(rule) {
		return
	}

	pass.Report(analysis.Diagnostic{
		Pos:            pos,
		Category:       rule,
		Message:        message,
		SuggestedFixes: fixes,
	})
}

// New creates a new Analyzer applying the given rules, or every rule when they are nil.
//
// The rules are read as the analyzer runs rather than as it is created, so a driver may
// bind them to flags declared on the Flags of the returned analyzer and have the parsed
// values take effect.
func New(opts *Options) *analysis.Analyzer {
	if opts == nil {
		opts = DefaultOptions()
	}

	linter := &linter{opts: opts}

	return &analysis.Analyzer{
		Name:     "mockerylint",
		Doc:      "Encourage good practices for mocks generated by Mockery",
		URL:      "https://github.com/mattdowdell/mockerylint#rules",
		Requires: []*analysis.Analyzer{inspect.Analyzer},
		Run:      linter.run,
	}
}

func (l *linter) run(pass *analysis.Pass) (any, error) {
	visitor, ok := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	if !ok {
		return nil, errors.New("missing inspect.Analyzer requirement")
	}

	// ast.IsGenerated walks the comments of a file, so it is answered once per file
	// rather than once per node. Generated files hold both the most comments and the
	// most nodes, which is where repeating the walk would cost the most.
	generated := make(map[*ast.File]bool, len(pass.Files))
	for _, file := range pass.Files {
		generated[file] = ast.IsGenerated(file)
	}

	filter := []ast.Node{
		(*ast.CallExpr)(nil),
		(*ast.CompositeLit)(nil),
		(*ast.ValueSpec)(nil),
	}

	visitor.WithStack(filter, func(n ast.Node, push bool, stack []ast.Node) bool {
		if push {
			l.visitWithContext(pass, n, stack, generated)
		}

		return true
	})

	return nil, nil
}

func (l *linter) visitWithContext(pass *analysis.Pass, node ast.Node, stack []ast.Node, generated map[*ast.File]bool) {
	// WithStack documents the first element of the stack as the enclosing *ast.File, so
	// the file needs no lookup.
	if file, ok := stack[0].(*ast.File); ok && generated[file] {
		return
	}

	switch n := node.(type) {
	case *ast.CallExpr:
		l.visitCallExpr(pass, n, stack)
	case *ast.CompositeLit:
		l.visitCompositeLit(pass, n)
	case *ast.ValueSpec:
		l.visitValueSpec(pass, n)
	}
}

func (l *linter) visitCallExpr(pass *analysis.Pass, call *ast.CallExpr, stack []ast.Node) {
	l.checkNewMockPattern(pass, call)
	l.checkAnythingArgs(pass, call)

	// Check for method calls on mock objects
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return
	}

	l.checkMockMethodCall(pass, call, selector, stack)
}

func (l *linter) checkNewMockPattern(pass *analysis.Pass, call *ast.CallExpr) {
	ident, ok := call.Fun.(*ast.Ident)
	if !ok || ident.Name != "new" {
		return
	}

	// new can be shadowed, so the name alone does not make this an allocation. A
	// function that happens to be called new allocates nothing.
	if _, ok := pass.TypesInfo.Uses[ident].(*types.Builtin); !ok {
		return
	}

	if len(call.Args) == 1 && isMockType(pass.TypesInfo.TypeOf(call.Args[0])) {
		l.report(pass, RuleUseFactory, call.Pos(), "use factory to initialise mock")
	}
}

// checkMockMethodCall reports on the method being called rather than on the receiver
// the chain starts from, so the diagnostic points at the offending call.
func (l *linter) checkMockMethodCall(pass *analysis.Pass, call *ast.CallExpr, selector *ast.SelectorExpr, stack []ast.Node) {
	switch selector.Sel.Name {
	case "On":
		// A mock generated without with-expecter has no expecter to migrate to, so
		// .On is the only way to set an expectation on it and reporting it would
		// leave no way to resolve the diagnostic.
		if typ := mockType(selector.X, pass.TypesInfo); hasExpecter(typ) {
			l.report(
				pass,
				RuleUseExpecter,
				selector.Sel.Pos(),
				"use .EXPECT instead of .On",
				expecterFixes(pass, call, selector, typ, stack)...,
			)
		}

	case "Test":
		if isMock(selector.X, pass.TypesInfo) {
			l.report(
				pass,
				RuleUseFactory,
				selector.Sel.Pos(),
				".Test() can be removed when using mock factory",
			)
		}

	case "AssertExpectations":
		if isMock(selector.X, pass.TypesInfo) {
			l.report(
				pass,
				RuleUseFactory,
				selector.Sel.Pos(),
				".AssertExpectations() can be removed when using mock factory",
			)
		}

	case "Return", "RunAndReturn":
		if isMockExpectationCall(selector.X, pass.TypesInfo) && needsTimesCall(stack) {
			l.report(
				pass,
				RuleUseTimes,
				selector.Sel.Pos(),
				`expectation should call .Maybe(), .Once(), .Twice(), or .Times(N)`,
			)
		}
	}
}

// expecterFixes returns the fix that rewrites an .On expectation into its expecter
// equivalent, e.g. m.On("Example", 1) into m.EXPECT().Example(1). The name of the mocked
// method moves out of the first argument and into the selector, so the two are edited
// together as a single fix.
//
// No fix is returned unless the rewrite is known to still compile. The .On form is loosely
// typed where the expecter form is not, so not every expectation has a mechanical rewrite,
// and one that does not is reported for the author to migrate by hand rather than fixed
// into something that does not build.
func expecterFixes(
	pass *analysis.Pass,
	call *ast.CallExpr,
	selector *ast.SelectorExpr,
	mockTyp types.Type,
	stack []ast.Node,
) []analysis.SuggestedFix {
	// The name of the mocked method is the first argument, and a spread argument cannot
	// be split into the fixed arguments an expecter method takes, so neither form can be
	// rewritten.
	if len(call.Args) == 0 || call.Ellipsis.IsValid() {
		return nil
	}

	mock := onMock(selector.X, pass.TypesInfo)
	if mock == nil {
		return nil
	}

	name, ok := methodName(call.Args[0], pass.TypesInfo)
	if !ok {
		return nil
	}

	// An expecter method is generated for each method of the mocked interface, so a name
	// it does not have, such as one left behind by a rename, has nothing to rewrite to.
	method := expecterMethod(pass.Pkg, mockTyp, name)
	if method == nil {
		return nil
	}

	if !argsAssignable(pass.TypesInfo, method, call.Args[1:]) {
		return nil
	}

	if !chainRewritable(pass, call, method.Results().At(0).Type(), stack) {
		return nil
	}

	// The argument naming the mocked method is dropped along with the comma separating
	// it from the next, so what remains lines up with the expecter method. An .On call
	// with no other arguments has no comma to remove.
	end := call.Args[0].End()
	if len(call.Args) > 1 {
		end = call.Args[1].Pos()
	}

	return []analysis.SuggestedFix{{
		Message: "Replace .On with .EXPECT()." + name,
		TextEdits: []analysis.TextEdit{
			{
				// Everything between the mock and the end of .On is replaced, so
				// the embedded testify mock of m.Mock.On(...) is dropped by the
				// same edit that rewrites the selector.
				Pos:     mock.End(),
				End:     selector.Sel.End(),
				NewText: []byte(".EXPECT()." + name),
			},
			{
				Pos: call.Args[0].Pos(),
				End: end,
			},
		},
	}}
}

// onMock returns the expression naming the mock that .On was called on, which is where the
// rewritten selector starts. The call may be written against the embedded testify mock,
// e.g. m.Mock.On(...), in which case the mock is one selector further in. A receiver in
// parentheses, e.g. (m.Mock).On(...), is not rewritten, as the closing parenthesis sits in
// the middle of what the edit would replace.
func onMock(expr ast.Expr, info *types.Info) ast.Expr {
	if selector, ok := expr.(*ast.SelectorExpr); ok && isTestifyMock(info.TypeOf(selector)) {
		if isMockType(info.TypeOf(selector.X)) {
			return selector.X
		}

		return nil
	}

	if isMockType(info.TypeOf(expr)) {
		return expr
	}

	return nil
}

// methodName returns the name of the mocked method that the first argument of .On holds.
// The constant value is read rather than the source text, so a name held in a constant
// resolves to the method it names just as testify resolves it.
func methodName(expr ast.Expr, info *types.Info) (string, bool) {
	value := info.Types[ast.Unparen(expr)].Value
	if value == nil || value.Kind() != constant.String {
		return "", false
	}

	return constant.StringVal(value), true
}

// expecterMethod returns the signature of the expecter method that replaces .On for the
// named mocked method, or nil when the expecter has no such method.
func expecterMethod(pkg *types.Package, mockTyp types.Type, name string) *types.Signature {
	expecter := expecterType(mockTyp)
	if expecter == nil {
		return nil
	}

	obj, _, _ := types.LookupFieldOrMethod(expecter, false, pkg, name)

	fn, ok := obj.(*types.Func)
	if !ok {
		return nil
	}

	// Each expecter method returns the generated expectation, so a signature that
	// returns anything else belongs to something other than a mocked method.
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Results().Len() != 1 {
		return nil
	}

	return sig
}

// chainRewritable reports whether the methods chained onto the .On call still compile once
// it is rewritten to the expecter form.
//
// The .On form returns testify's *mock.Call, whilst the expecter form returns the
// generated expectation, which shadows Run and Return with typed versions. An argument the
// typed version does not accept, such as the function .Return takes to compute a return
// value dynamically, has no mechanical rewrite, as the expecter spells that as
// .RunAndReturn instead.
//
// The chain is walked outwards from the .On call. Once it reaches a method promoted from
// the embedded *mock.Call, the rest of the chain resolves exactly as it did before, so the
// walk stops there. An expectation that escapes into a variable, return value or argument
// whilst it is still the generated expectation cannot be judged, as whatever receives it
// was written to accept a *mock.Call.
func chainRewritable(pass *analysis.Pass, call *ast.CallExpr, expectation types.Type, stack []ast.Node) bool {
	node := ast.Node(call)
	parents := stack[:len(stack)-1]

	// The signature of the method the chain has selected but not yet called.
	var pending *types.Signature

	for _, p := range slices.Backward(parents) {
		switch parent := p.(type) {
		case *ast.ParenExpr:
			// Parentheses do not break the chain.

		case *ast.SelectorExpr:
			if pending = chainMethod(pass.Pkg, expectation, parent, node); pending == nil {
				return false
			}

		case *ast.CallExpr:
			expectation = chainResult(pass.TypesInfo, parent, pending, node)
			if expectation == nil {
				return false
			}

			pending = nil

			// A method promoted from the embedded *mock.Call returns that
			// rather than the generated expectation, so the chain has left the
			// part of itself the rewrite changes.
			if isTestifyCall(expectation) {
				return true
			}

		case *ast.ExprStmt:
			// The chain ends and its value is discarded, so nothing observes
			// the expectation taking a new type.
			return true

		default:
			return false
		}

		node = p
	}

	return false
}

// chainMethod returns the signature of the method the selector reads from the expectation
// the chain has reached, or nil when the chain cannot be followed any further. The
// expectation being anything other than the receiver of the selector means it escapes,
// e.g. as the operand of a comparison.
func chainMethod(
	pkg *types.Package,
	expectation types.Type,
	selector *ast.SelectorExpr,
	node ast.Node,
) *types.Signature {
	if selector.X != node {
		return nil
	}

	obj, _, _ := types.LookupFieldOrMethod(expectation, false, pkg, selector.Sel.Name)

	fn, ok := obj.(*types.Func)
	if !ok {
		return nil
	}

	// Every method of an expectation returns one value to chain from, so a signature
	// that returns anything else ends the chain.
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Results().Len() != 1 {
		return nil
	}

	return sig
}

// chainResult returns the type the selected method yields once called, or nil when the
// call cannot be rewritten. The expectation being anything other than the function being
// called means it escapes, e.g. as an argument of another call.
func chainResult(
	info *types.Info,
	call *ast.CallExpr,
	selected *types.Signature,
	node ast.Node,
) types.Type {
	if selected == nil || call.Fun != node {
		return nil
	}

	if call.Ellipsis.IsValid() || !argsAssignable(info, selected, call.Args) {
		return nil
	}

	return selected.Results().At(0).Type()
}

// argsAssignable reports whether the arguments can be passed to the signature. The
// rewritten chain is not type checked as a whole, so each call whose meaning the rewrite
// changes is checked here instead.
func argsAssignable(info *types.Info, sig *types.Signature, args []ast.Expr) bool {
	params := sig.Params()

	switch {
	case sig.Variadic():
		if len(args) < params.Len()-1 {
			return false
		}
	case len(args) != params.Len():
		return false
	}

	for i, arg := range args {
		typ := info.TypeOf(arg)
		if typ == nil {
			return false
		}

		want := params.At(min(i, params.Len()-1)).Type()

		// An argument at or past the final parameter of a variadic signature is
		// assigned to the element of the slice it collects into.
		if sig.Variadic() && i >= params.Len()-1 {
			slice, ok := want.(*types.Slice)
			if !ok {
				return false
			}

			want = slice.Elem()
		}

		if !types.AssignableTo(typ, want) {
			return false
		}
	}

	return true
}

// checkAnythingArgs reports each argument of an expectation that matches anything at all.
// The diagnostic points at the argument rather than the call, so an expectation with one
// offending argument amongst several says which.
func (l *linter) checkAnythingArgs(pass *analysis.Pass, call *ast.CallExpr) {
	for _, arg := range expectationArgs(pass, call) {
		if isAnything(arg, pass.TypesInfo) {
			l.report(
				pass,
				RuleNoAnything,
				arg.Pos(),
				"use the expected value, mock.AnythingOfType, or mock.MatchedBy instead of mock.Anything",
			)
		}
	}
}

// expectationArgs returns the arguments of the call that match the arguments of a mocked
// method, or nil when the call matches no arguments.
func expectationArgs(pass *analysis.Pass, call *ast.CallExpr) []ast.Expr {
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return nil
	}

	// The expecter form, e.g. m.EXPECT().Example(...), takes one argument per argument
	// of the mocked method and returns the generated expectation. The methods chained
	// onto that expectation, such as .Return, return it again, so the receiver being an
	// expecter rather than an expectation is what tells the two apart. Without that, the
	// return values given to .Return would be matched as if they were arguments.
	if isMockExpectationCall(call, pass.TypesInfo) && !isMockExpectationCall(selector.X, pass.TypesInfo) {
		return call.Args
	}

	// The .On form, e.g. m.On("Example", ...), names the mocked method in its first
	// argument and matches the arguments of the method with the rest. It returns a
	// *mock.Call, which embeds no expectation, so the expecter form above does not
	// cover it.
	if selector.Sel.Name == "On" && len(call.Args) > 0 && isMock(selector.X, pass.TypesInfo) {
		return call.Args[1:]
	}

	return nil
}

// isAnything reports whether the expression matches any argument at all. The constant
// value is compared rather than the name the expression is written as, so an alias for
// mock.Anything or the string it holds spelled out in full is matched too. Testify
// compares the argument by value, so it treats all three the same way.
func isAnything(expr ast.Expr, info *types.Info) bool {
	value := info.Types[ast.Unparen(expr)].Value
	if value == nil || value.Kind() != constant.String {
		return false
	}

	return constant.StringVal(value) == "mock.Anything"
}

// isTimesMethod matched the expectation methods that constrain how many times a mocked
// method is expected to be called.
func isTimesMethod(name string) bool {
	switch name {
	case "Maybe", "Once", "Twice", "Times":
		return true
	default:
		return false
	}
}

// needsTimesCall reports whether the expectation call at the top of stack is missing
// a call to one of the timesMethods.
//
// The stack is walked outwards along the expectation chain. A times method anywhere
// in the chain satisfies the rule, and so does an expectation that escapes into a
// variable, return value or argument, because a times method may be called on it
// elsewhere. Only a chain whose value is discarded can be reported with confidence.
func needsTimesCall(stack []ast.Node) bool {
	if len(stack) == 0 {
		return false
	}

	node := stack[len(stack)-1]
	parents := stack[:len(stack)-1]

	for _, p := range slices.Backward(parents) {
		switch parent := p.(type) {
		case *ast.ParenExpr:
			// Parentheses do not break the chain.

		case *ast.SelectorExpr:
			// The expectation is the receiver of another chained method.
			if parent.X != node {
				return false
			}

			if isTimesMethod(parent.Sel.Name) {
				return false
			}

		case *ast.CallExpr:
			// The chained method is being called, e.g. the parentheses in .Run(f). If
			// the expectation is an argument instead, it escapes.
			if parent.Fun != node {
				return false
			}

		case *ast.ExprStmt:
			// The chain ends without a times method and its value is discarded.
			return true

		default:
			// The expectation escapes, so it cannot be judged in isolation.
			return false
		}

		node = p
	}

	return false
}

// visitCompositeLit checks for mocks initialised with a composite literal, covering
// both the MockExample{} and &MockExample{} forms. The literal is reported rather than
// any enclosing &, so the two are handled by one check.
func (l *linter) visitCompositeLit(pass *analysis.Pass, comp *ast.CompositeLit) {
	if isMockType(pass.TypesInfo.TypeOf(comp)) {
		l.report(pass, RuleUseFactory, comp.Pos(), "use factory to initialise mock")
	}
}

// visitValueSpec checks for mocks left at their zero value, e.g. var m MockExample. A
// zero valued mock is usable, so it bypasses the factory just as a composite literal
// does. Declaring a pointer to a mock creates nothing and is left alone, as it is the
// usual way to hold a mock the factory returns later.
func (l *linter) visitValueSpec(pass *analysis.Pass, spec *ast.ValueSpec) {
	if spec.Type == nil || len(spec.Values) > 0 {
		return
	}

	typ := pass.TypesInfo.TypeOf(spec.Type)
	if _, ok := typ.(*types.Pointer); ok {
		return
	}

	if isMockType(typ) {
		l.report(pass, RuleUseFactory, spec.Pos(), "use factory to initialise mock")
	}
}

// isMock reports whether the expression refers to a mock generated by Mockery, either
// the mock itself or the testify mock.Mock it embeds.
func isMock(expr ast.Expr, info *types.Info) bool {
	return mockType(expr, info) != nil
}

// mockType returns the type of the mock generated by Mockery that the expression refers
// to, or nil when it refers to no such mock. The expression may be the mock itself or the
// testify mock.Mock it embeds, and in both cases the type of the generated mock is
// returned, so a check on what Mockery generated for it reads the same either way.
func mockType(expr ast.Expr, info *types.Info) types.Type {
	expr = ast.Unparen(expr)

	// The generated mock, e.g. the m in m.Test(t).
	if typ := info.TypeOf(expr); isMockType(typ) {
		return typ
	}

	// The embedded testify mock, e.g. the m.Mock in m.Mock.Test(t). A mock.Mock that is
	// not embedded in a generated mock has no factory to migrate to, so a selector on a
	// generated mock is required rather than the mock.Mock type alone.
	if selector, ok := expr.(*ast.SelectorExpr); ok && isTestifyMock(info.TypeOf(expr)) {
		if typ := info.TypeOf(selector.X); isMockType(typ) {
			return typ
		}
	}

	return nil
}

// hasExpecter reports whether the mock type has the EXPECT method that returns its
// expecter.
func hasExpecter(typ types.Type) bool {
	return expecterType(typ) != nil
}

// expecterType returns the type of the expecter that the EXPECT method of the mock
// returns, or nil when the mock has no such method. Mockery generates EXPECT only when
// with-expecter is enabled, which it always is since v3.0.0, so an older mock generated
// without it has no expecter at all.
func expecterType(typ types.Type) types.Type {
	if typ == nil {
		return nil
	}

	if ptr, ok := typ.(*types.Pointer); ok {
		typ = ptr.Elem()
	}

	// EXPECT is generated with a pointer receiver, so the method set of the pointer is
	// searched rather than that of the mock itself.
	obj, _, _ := types.LookupFieldOrMethod(types.NewPointer(typ), false, nil, "EXPECT")

	fn, ok := obj.(*types.Func)
	if !ok {
		return nil
	}

	// A mocked method that happens to be called EXPECT is generated the same way as any
	// other, so the signature is checked to tell it from the expecter accessor.
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Params().Len() != 0 || sig.Results().Len() != 1 {
		return nil
	}

	return sig.Results().At(0).Type()
}

// isTestifyMock reports whether the type is testify's mock.Mock.
func isTestifyMock(typ types.Type) bool {
	return typ != nil && typ.String() == "github.com/stretchr/testify/mock.Mock"
}

// isTestifyCall reports whether the type is testify's *mock.Call.
func isTestifyCall(typ types.Type) bool {
	return typ != nil && typ.String() == "*github.com/stretchr/testify/mock.Call"
}

func isMockType(typ types.Type) bool {
	if typ == nil {
		return false
	}

	// Handle pointer types
	ptr, ok := typ.(*types.Pointer)
	if ok {
		typ = ptr.Elem()
	}

	// Get the underlying struct
	var structType *types.Struct
	switch t := typ.(type) {
	case *types.Struct:
		structType = t
	case *types.Named:
		if s, ok := t.Underlying().(*types.Struct); ok {
			structType = s
		}
	}

	if structType == nil {
		return false
	}

	// Check if the struct has an embedded mock.Mock field
	for field := range structType.Fields() {
		if !field.Embedded() {
			continue
		}

		if isTestifyMock(field.Type()) {
			return true
		}
	}

	return false
}

// isMockExpectationCall checks if the expression is a call to a mock expectation method
// (e.g., the result of m.EXPECT().Example(...)).
func isMockExpectationCall(expr ast.Expr, info *types.Info) bool {
	typ := info.TypeOf(expr)
	if typ == nil {
		return false
	}

	// Check if the type is a pointer to a type that embeds *mock.Call
	// The pattern is: *MockExample_Example_Call which embeds *mock.Call
	ptr, ok := typ.(*types.Pointer)
	if !ok {
		return false
	}

	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return false
	}

	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return false
	}

	// Check if the struct has an embedded *mock.Call field
	for field := range structType.Fields() {
		if !field.Embedded() {
			continue
		}

		if isTestifyCall(field.Type()) {
			return true
		}
	}

	return false
}
