package mockerylint

import (
	"errors"
	"flag"
	"go/ast"
	"go/token"
	"go/types"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

// The rules the analyzer applies. Each name matches the heading of its section in the
// README, so a diagnostic categorised with one resolves to that section, and each names
// the flag that turns the rule off.
const (
	ruleUseFactory  = "usefactory"
	ruleUseExpecter = "useexpecter"
	ruleUseTimes    = "usetimes"
)

// rules records which of the rules the analyzer applies. Every rule is applied unless
// its flag says otherwise, so the zero value applies none and register is what makes an
// unconfigured analyzer behave as it did before the rules could be turned off.
type rules struct {
	useFactory  bool
	useExpecter bool
	useTimes    bool
}

// register declares the flag that turns each rule off, e.g. -usetimes=false.
func (r *rules) register(flags *flag.FlagSet) {
	flags.BoolVar(&r.useFactory, ruleUseFactory, true, "apply the "+ruleUseFactory+" rule")
	flags.BoolVar(&r.useExpecter, ruleUseExpecter, true, "apply the "+ruleUseExpecter+" rule")
	flags.BoolVar(&r.useTimes, ruleUseTimes, true, "apply the "+ruleUseTimes+" rule")
}

// enabled reports whether the named rule is applied. A name with no flag of its own is
// applied, so a rule added without one keeps the behaviour it had before rather than
// disappearing from the output unannounced.
func (r *rules) enabled(rule string) bool {
	switch rule {
	case ruleUseFactory:
		return r.useFactory
	case ruleUseExpecter:
		return r.useExpecter
	case ruleUseTimes:
		return r.useTimes
	default:
		return true
	}
}

// linter holds the configuration the checks share. Each call to New builds its own, so
// the rules turned off for one analyzer have no effect on another.
type linter struct {
	rules rules
}

// report records a diagnostic against the rule that produced it, unless that rule is
// turned off. Every check reports through here, so no disabled rule can reach the
// output. A driver resolves the documentation for a categorised diagnostic as "#" +
// category relative to the URL of the analyzer, which is the rule's heading in the
// README.
func (l *linter) report(pass *analysis.Pass, rule string, pos token.Pos, message string) {
	if !l.rules.enabled(rule) {
		return
	}

	pass.Report(analysis.Diagnostic{
		Pos:      pos,
		Category: rule,
		Message:  message,
	})
}

// New creates a new Analyzer.
func New() *analysis.Analyzer {
	linter := &linter{}

	analyzer := &analysis.Analyzer{
		Name:     "mockerylint",
		Doc:      "Encourage good practices for mocks generated by Mockery",
		URL:      "https://github.com/mattdowdell/mockerylint#rules",
		Requires: []*analysis.Analyzer{inspect.Analyzer},
		Run:      linter.run,
	}

	linter.rules.register(&analyzer.Flags)

	return analyzer
}

func (l *linter) run(pass *analysis.Pass) (any, error) {
	visitor, ok := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	if !ok {
		return nil, errors.New("missing inspect.Analyzer requirement")
	}

	// ast.IsGenerated walks the comments of a file, so it is answered once per file
	// rather than once per node. Generated files hold both the most comments and the
	// most nodes, which is where repeating the walk would cost the most.
	generated := make(map[*ast.File]bool, len(pass.Files))
	for _, file := range pass.Files {
		generated[file] = ast.IsGenerated(file)
	}

	filter := []ast.Node{
		(*ast.CallExpr)(nil),
		(*ast.CompositeLit)(nil),
		(*ast.ValueSpec)(nil),
	}

	visitor.WithStack(filter, func(n ast.Node, push bool, stack []ast.Node) bool {
		if push {
			l.visitWithContext(pass, n, stack, generated)
		}

		return true
	})

	return nil, nil
}

func (l *linter) visitWithContext(pass *analysis.Pass, node ast.Node, stack []ast.Node, generated map[*ast.File]bool) {
	// WithStack documents the first element of the stack as the enclosing *ast.File, so
	// the file needs no lookup.
	if file, ok := stack[0].(*ast.File); ok && generated[file] {
		return
	}

	switch n := node.(type) {
	case *ast.CallExpr:
		l.visitCallExpr(pass, n, stack)
	case *ast.CompositeLit:
		l.visitCompositeLit(pass, n)
	case *ast.ValueSpec:
		l.visitValueSpec(pass, n)
	}
}

func (l *linter) visitCallExpr(pass *analysis.Pass, call *ast.CallExpr, stack []ast.Node) {
	l.checkNewMockPattern(pass, call)

	// Check for method calls on mock objects
	selector, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return
	}

	l.checkMockMethodCall(pass, selector, stack)
}

func (l *linter) checkNewMockPattern(pass *analysis.Pass, call *ast.CallExpr) {
	ident, ok := call.Fun.(*ast.Ident)
	if !ok || ident.Name != "new" {
		return
	}

	// new can be shadowed, so the name alone does not make this an allocation. A
	// function that happens to be called new allocates nothing.
	if _, ok := pass.TypesInfo.Uses[ident].(*types.Builtin); !ok {
		return
	}

	if len(call.Args) == 1 && isMockType(pass.TypesInfo.TypeOf(call.Args[0])) {
		l.report(pass, ruleUseFactory, call.Pos(), "use factory to initialise mock")
	}
}

// checkMockMethodCall reports on the method being called rather than on the receiver
// the chain starts from, so the diagnostic points at the offending call.
func (l *linter) checkMockMethodCall(pass *analysis.Pass, selector *ast.SelectorExpr, stack []ast.Node) {
	switch selector.Sel.Name {
	case "On":
		if isMock(selector.X, pass.TypesInfo) {
			l.report(pass, ruleUseExpecter, selector.Sel.Pos(), "use .EXPECT instead of .On")
		}

	case "Test":
		if isMock(selector.X, pass.TypesInfo) {
			l.report(pass, ruleUseFactory, selector.Sel.Pos(), ".Test() can be removed when using mock factory")
		}

	case "AssertExpectations":
		if isMock(selector.X, pass.TypesInfo) {
			l.report(pass, ruleUseFactory, selector.Sel.Pos(), ".AssertExpectations() can be removed when using mock factory")
		}

	case "Return", "RunAndReturn":
		if isMockExpectationCall(selector.X, pass.TypesInfo) && needsTimesCall(stack) {
			l.report(pass, ruleUseTimes, selector.Sel.Pos(), `expectation should call .Maybe(), .Once(), .Twice(), or .Times(N)`)
		}
	}
}

// isTimesMethod matched the expectation methods that constrain how many times a mocked
// method is expected to be called.
func isTimesMethod(name string) bool {
	switch name {
	case "Maybe", "Once", "Twice", "Times":
		return true
	default:
		return false
	}
}

// needsTimesCall reports whether the expectation call at the top of stack is missing
// a call to one of the timesMethods.
//
// The stack is walked outwards along the expectation chain. A times method anywhere
// in the chain satisfies the rule, and so does an expectation that escapes into a
// variable, return value or argument, because a times method may be called on it
// elsewhere. Only a chain whose value is discarded can be reported with confidence.
func needsTimesCall(stack []ast.Node) bool {
	if len(stack) == 0 {
		return false
	}

	node := stack[len(stack)-1]
	parents := stack[:len(stack)-1]

	for i := len(parents) - 1; i >= 0; i-- {
		switch parent := parents[i].(type) {
		case *ast.ParenExpr:
			// Parentheses do not break the chain.

		case *ast.SelectorExpr:
			// The expectation is the receiver of another chained method.
			if parent.X != node {
				return false
			}

			if isTimesMethod(parent.Sel.Name) {
				return false
			}

		case *ast.CallExpr:
			// The chained method is being called, e.g. the parentheses in .Run(f). If
			// the expectation is an argument instead, it escapes.
			if parent.Fun != node {
				return false
			}

		case *ast.ExprStmt:
			// The chain ends without a times method and its value is discarded.
			return true

		default:
			// The expectation escapes, so it cannot be judged in isolation.
			return false
		}

		node = parents[i]
	}

	return false
}

// visitCompositeLit checks for mocks initialised with a composite literal, covering
// both the MockExample{} and &MockExample{} forms. The literal is reported rather than
// any enclosing &, so the two are handled by one check.
func (l *linter) visitCompositeLit(pass *analysis.Pass, comp *ast.CompositeLit) {
	if isMockType(pass.TypesInfo.TypeOf(comp)) {
		l.report(pass, ruleUseFactory, comp.Pos(), "use factory to initialise mock")
	}
}

// visitValueSpec checks for mocks left at their zero value, e.g. var m MockExample. A
// zero valued mock is usable, so it bypasses the factory just as a composite literal
// does. Declaring a pointer to a mock creates nothing and is left alone, as it is the
// usual way to hold a mock the factory returns later.
func (l *linter) visitValueSpec(pass *analysis.Pass, spec *ast.ValueSpec) {
	if spec.Type == nil || len(spec.Values) > 0 {
		return
	}

	typ := pass.TypesInfo.TypeOf(spec.Type)
	if _, ok := typ.(*types.Pointer); ok {
		return
	}

	if isMockType(typ) {
		l.report(pass, ruleUseFactory, spec.Pos(), "use factory to initialise mock")
	}
}

// isMock reports whether the expression refers to a mock generated by Mockery, either
// the mock itself or the testify mock.Mock it embeds.
func isMock(expr ast.Expr, info *types.Info) bool {
	expr = ast.Unparen(expr)

	// The generated mock, e.g. the m in m.Test(t).
	if isMockType(info.TypeOf(expr)) {
		return true
	}

	// The embedded testify mock, e.g. the m.Mock in m.Mock.Test(t). A mock.Mock that is
	// not embedded in a generated mock has no factory to migrate to, so a selector on a
	// generated mock is required rather than the mock.Mock type alone.
	if selector, ok := expr.(*ast.SelectorExpr); ok {
		return isTestifyMock(info.TypeOf(expr)) && isMockType(info.TypeOf(selector.X))
	}

	return false
}

// isTestifyMock reports whether the type is testify's mock.Mock.
func isTestifyMock(typ types.Type) bool {
	return typ != nil && typ.String() == "github.com/stretchr/testify/mock.Mock"
}

func isMockType(typ types.Type) bool {
	if typ == nil {
		return false
	}

	// Handle pointer types
	ptr, ok := typ.(*types.Pointer)
	if ok {
		typ = ptr.Elem()
	}

	// Get the underlying struct
	var structType *types.Struct
	switch t := typ.(type) {
	case *types.Struct:
		structType = t
	case *types.Named:
		if s, ok := t.Underlying().(*types.Struct); ok {
			structType = s
		}
	}

	if structType == nil {
		return false
	}

	// Check if the struct has an embedded mock.Mock field
	for i := range structType.NumFields() {
		field := structType.Field(i)
		if !field.Embedded() {
			continue
		}

		if isTestifyMock(field.Type()) {
			return true
		}
	}

	return false
}

// isMockExpectationCall checks if the expression is a call to a mock expectation method
// (e.g., the result of m.EXPECT().Example(...)).
func isMockExpectationCall(expr ast.Expr, info *types.Info) bool {
	typ := info.TypeOf(expr)
	if typ == nil {
		return false
	}

	// Check if the type is a pointer to a type that embeds *mock.Call
	// The pattern is: *MockExample_Example_Call which embeds *mock.Call
	ptr, ok := typ.(*types.Pointer)
	if !ok {
		return false
	}

	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return false
	}

	structType, ok := named.Underlying().(*types.Struct)
	if !ok {
		return false
	}

	// Check if the struct has an embedded *mock.Call field
	for i := range structType.NumFields() {
		field := structType.Field(i)
		if !field.Embedded() {
			continue
		}

		fieldType := field.Type()
		if fieldType.String() == "*github.com/stretchr/testify/mock.Call" {
			return true
		}
	}

	return false
}
