// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usefactory

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExample creates a new instance of MockExample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExample(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExample {
	mock := &MockExample{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExample is an autogenerated mock type for the Example type
type MockExample struct {
	mock.Mock
}

type MockExample_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExample) EXPECT() *MockExample_Expecter {
	return &MockExample_Expecter{mock: &_m.Mock}
}

// Example provides a mock function for the type MockExample
func (_mock *MockExample) Example(n int) int {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Example")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockExample_Example_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Example'
type MockExample_Example_Call struct {
	*mock.Call
}

// Example is a helper method to define mock.On call
//   - n int
func (_e *MockExample_Expecter) Example(n interface{}) *MockExample_Example_Call {
	return &MockExample_Example_Call{Call: _e.mock.On("Example", n)}
}

func (_c *MockExample_Example_Call) Run(run func(n int)) *MockExample_Example_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExample_Example_Call) Return(n1 int) *MockExample_Example_Call {
	_c.Call.Return(n1)
	return _c
}

func (_c *MockExample_Example_Call) RunAndReturn(run func(n int) int) *MockExample_Example_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExampleParam creates a new instance of MockExampleParam. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExampleParam[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExampleParam[T] {
	mock := &MockExampleParam[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExampleParam is an autogenerated mock type for the ExampleParam type
type MockExampleParam[T any] struct {
	mock.Mock
}

type MockExampleParam_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockExampleParam[T]) EXPECT() *MockExampleParam_Expecter[T] {
	return &MockExampleParam_Expecter[T]{mock: &_m.Mock}
}

// Example provides a mock function for the type MockExampleParam
func (_mock *MockExampleParam[T]) Example(v T) T {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Example")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func(T) T); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockExampleParam_Example_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Example'
type MockExampleParam_Example_Call[T any] struct {
	*mock.Call
}

// Example is a helper method to define mock.On call
//   - v T
func (_e *MockExampleParam_Expecter[T]) Example(v interface{}) *MockExampleParam_Example_Call[T] {
	return &MockExampleParam_Example_Call[T]{Call: _e.mock.On("Example", v)}
}

func (_c *MockExampleParam_Example_Call[T]) Run(run func(v T)) *MockExampleParam_Example_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExampleParam_Example_Call[T]) Return(v1 T) *MockExampleParam_Example_Call[T] {
	_c.Call.Return(v1)
	return _c
}

func (_c *MockExampleParam_Example_Call[T]) RunAndReturn(run func(v T) T) *MockExampleParam_Example_Call[T] {
	_c.Call.Return(run)
	return _c
}
