// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

// Package mocks holds a mock generated into a package of its own, as Mockery is often
// configured to do.
package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOther creates a new instance of MockOther. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOther(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOther {
	mock := &MockOther{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOther is an autogenerated mock type for the Other type
type MockOther struct {
	mock.Mock
}
