---

name: Label

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  size:
    name: Size
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      pull-requests: write # for managing labels
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Size
        id: size
        uses: mattdowdell/pr-sizer@ee8ce3fa199d4fb213b010253e362216d26463c4 # v0.5.2

      - name: Outputs
        run: |
          echo size=${SIZE}
          echo includes=${INCLUDES}
          echo excludes=${EXCLUDES}
          echo ignores=${IGNORES}
        env:
          SIZE: ${{ steps.size.outputs.size }}
          INCLUDES: ${{ steps.size.outputs.includes }}
          EXCLUDES: ${{ steps.size.outputs.excludes }}
          IGNORES: ${{ steps.size.outputs.ignores }}
